num=input("enter a number")
num=int(num)
print("The result of", num, "* 1 is:", num*1)
print("The result of", num, "* 2 is:", num*2)
print("The result of", num, "* 3 is:", num*3)
print("The result of", num, "* 4 is:", num*4)
print("The result of", num, "* 5 is:", num*5)
print("The result of", num, "* 6 is:", num*6)
print("The result of", num, "* 7 is:", num*7)
print("The result of", num, "* 8 is:", num*8)
print("The result of", num, "* 9 is:", num*9)
print("The result of", num, "* 10 is:", num*10)
print("The result of", num, "* 11 is:", num*11)
print("The result of", num, "* 12 is:", num*12)